imports:
    - { resource: "@TipddyBackendBundle/Resources/config/services.yml"}


# Services configuration
services:
    twig.extension.text:
        class: Twig_Extensions_Extension_Text
        tags:
            - { name: twig.extension }
    twig.extension.debug:
        class: Twig_Extensions_Extension_Debug
        tags:
            - { name: twig.extension }      
            
    twig.extension.tipsurvey:
        class: Tipddy\BackendBundle\Twig\Extension\UtilExtension
        tags:
            - { name: twig.extension }      
            
