parameters:
#    tipddy_security.example.class: Tipddy\SecurityBundle\Example

services:
#    tipddy_security.example:
#        class: %tipddy_security.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
