parameters:
#    tipddy_backend.example.class: Tipddy\BackendBundle\Example

services:
#    tipddy_backend.example:
#        class: %tipddy_backend.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
