parameters:


services:
    tipddy_backend.filterchain:
        class: Tipddy\BackendBundle\Listener\SessionControlListener  
        arguments: [@service_container, @session]
        tags:
            - { name: kernel.event_listener, event: kernel.request, priority: -100 }
